build duckdb and python-duckdb packages
conda-forge/python-duckdb-feedstock pull request #105
Opened 2024-05-15 12:56 UTC by ytausch

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

We now build `duckdb` next to the `python-duckdb` package because `duckdb` once was a duplicate of `python-duckdb`.

See https://github.com/conda-forge/duckdb-feedstock/issues/6

@xhochy Does this work like this or do we have to whitelist this feedstock so it can build the `duckdb` package?

2024-05-17 12:24 UTC, xhochy commented on recipe/meta.yaml
> +        - {{ compiler('c') }}
```suggestion
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
```

2024-05-17 12:24 UTC, xhochy commented on recipe/meta.yaml
> +        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
```suggestion
```

2024-05-17 12:25 UTC, xhochy commented
To make this work, you need to delete `recipe/conda_build_config.yaml`

2024-05-21 11:03 UTC, ytausch commented
@xhochy Do you know what fails now? The error is sadly not very descriptive

2024-05-21 11:16 UTC, xhochy commented on recipe/meta.yaml
> +          - {{ pin_subpackage('python-duckdb', max_pin="x.x.x") }}
```suggestion
          - python-duckdb {{ version }}
```

2024-05-21 14:46 UTC, ytausch commented
@xhochy This doesn't seem to have helped - and also, I saw `pin_subpackage` in [various places](https://github.com/conda-forge/py-rattler-feedstock/blob/main/recipe/meta.yaml) for aliased package outputs.

2024-05-21 18:39 UTC, xhochy commented
> @xhochy This doesn't seem to have helped - and also, I saw `pin_subpackage` in [various places](https://github.com/conda-forge/py-rattler-feedstock/blob/main/recipe/meta.yaml) for aliased package outputs.

Yes, then it's best probably to revert here

2024-05-21 18:40 UTC, xhochy requested changes

2024-05-21 18:40 UTC, xhochy commented on recipe/meta.yaml
> +      requirements:
@ytausch This is the actual issue 😂 
```suggestion
    requirements:
```

2024-05-22 13:45 UTC, ytausch commented on recipe/meta.yaml
> +      requirements:
Oh no, yes xD

2024-05-22 16:25 UTC, xhochy approved these changes

2024-05-22 16:25 UTC, merged